version: '3.9'
services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_USER=root